# Villagers Names Configuration file
# Created by Mancdev.com

#
# Enable to show villager names without hovering over them
name_visible: true

#
# Potential chance that a villager will have a custom name
# (1.0 = 100% chance of spawning with name)
# (0.45 = 45% chance of spawning with name)
name_potential: 0.45

#
# Full display names for Villager
display_name: "%custom_name%"
display_name_with_profession: "%custom_name% The %profession%"

#
# List of villager names
# ChatColor formatting: https://minecraft.gamepedia.com/Formatting_codes
# i.e. - "§c Jessie" will be displayed as red
villager_names:
  - "§cJessie"
  - "§9James"
  - "Abbas"
  - "Abdel"
  - "Abdo"
  - "Abdoulaye"
  - "Abdul"
  - "Abdullah"
  - "Abdullahi"
  - "Abel"
  - "Abraham"
  - "Abubakar"
  - "Adam"
  - "Adama"
  - "Adamu"
  - "Adel"
  - "Adelaide"
  - "Adrian"
  - "Adriana"
  - "Agnes"
  - "Agus"
  - "Ahmad"
  - "Ahmed"
  - "Ahmet"
  - "Ai"
  - "Aicha"
  - "Aida"
  - "Aisha"
  - "Ajay"
  - "Alaa"
  - "Alain"
  - "Alan"
  - "Albert"
  - "Alberto"
  - "Aleida"
  - "Alejandro"
  - "Aleksandr"
  - "Aleksandra"
  - "Aleksey"
  - "Alex"
  - "Alexander"
  - "Alexandra"
  - "Alexandre"
  - "Alexey"
  - "Alexia"
  - "Alfred"
  - "Alfredo"
  - "Ali"
  - "Alianor"
  - "Alice"
  - "Alicia"
  - "Alina"
  - "Aliyu"
  - "Alma"
  - "Althalos"
  - "Alys"
  - "Amadou"
  - "Amal"
  - "Amanda"
  - "Amar"
  - "Amelia"
  - "Amin"
  - "Amina"
  - "Aminata"
  - "Amir"
  - "Amit"
  - "Amy"
  - "An"
  - "Ana"
  - "Anastas"
  - "Anastasia"
  - "Anastasiya"
  - "Andre"
  - "Andrea"
  - "Andreas"
  - "Andrei"
  - "Andres"
  - "Andrew"
  - "Andrey"
  - "Angel"
  - "Angela"
  - "Angelica"
  - "Angelina"
  - "Angelo"
  - "Angmar"
  - "Anh"
  - "Anil"
  - "Anita"
  - "Ann"
  - "Anna"
  - "Anne"
  - "Annie"
  - "Anthony"
  - "Anton"
  - "Antonia"
  - "Antonio"
  - "António"
  - "Anwar"
  - "Arabella"
  - "Ariana"
  - "Arif"
  - "Arjun"
  - "Armando"
  - "Arthur"
  - "Artur"
  - "Arturo"
  - "Artyom"
  - "Arun"
  - "Asha"
  - "Asher"
  - "Ashok"
  - "Ashraf"
  - "Asma"
  - "Asmaa"
  - "Atheena"
  - "Aung"
  - "Aya"
  - "Ayesha"
  - "Ayleth"
  - "Ayşe"
  - "Aziz"
  - "Babu"
  - "Barbara"
  - "Barda"
  - "Basanti"
  - "Bashir"
  - "Beatrice"
  - "Beatrix"
  - "Beatriz"
  - "Bekele"
  - "Benedict"
  - "Benjamin"
  - "Berinon"
  - "Bernadette"
  - "Bernard"
  - "Betty"
  - "Bharat"
  - "Bibi"
  - "Bin"
  - "Blanca"
  - "Blessing"
  - "Borin"
  - "Brangian"
  - "Brenda"
  - "Brian"
  - "Brigitte"
  - "Brom"
  - "Brunhild"
  - "Bruno"
  - "Bryce"
  - "Ca"
  - "Carac"
  - "Carla"
  - "Carlos"
  - "Carmen"
  - "Carol"
  - "Carolina"
  - "Caroline"
  - "Cassius"
  - "Catherine"
  - "Catrain"
  - "Cecilia"
  - "Cedany"
  - "Cedric"
  - "Cesar"
  - "Chandra"
  - "Chantal"
  - "Chao"
  - "Charles"
  - "Charlotte"
  - "Chen"
  - "Cheng"
  - "Cheryl"
  - "Chi"
  - "Chris"
  - "Christian"
  - "Christina"
  - "Christine"
  - "Christophe"
  - "Christopher"
  - "Chun"
  - "Chunhua"
  - "Chunyan"
  - "Clara"
  - "Claude"
  - "Claudia"
  - "Claudio"
  - "Cong"
  - "Cristian"
  - "Cristiana"
  - "Cristina"
  - "Cynthia"
  - "Dain"
  - "Dan"
  - "Daniel"
  - "Daniela"
  - "Darya"
  - "David"
  - "Deborah"
  - "Deepak"
  - "Denis"
  - "Denise"
  - "Dennis"
  - "Destrian"
  - "Di"
  - "Diana"
  - "Diane"
  - "Diego"
  - "Dilip"
  - "Dimia"
  - "Dina"
  - "Dinesh"
  - "Dipak"
  - "Dmitriy"
  - "Dmitry"
  - "Dolores"
  - "Dominique"
  - "Donald"
  - "Dongmei"
  - "Donna"
  - "Dora"
  - "Doran"
  - "Doris"
  - "Dorothy"
  - "Douglas"
  - "Dung"
  - "Duraina"
  - "Durga"
  - "Earl"
  - "Edgar"
  - "Edith"
  - "Edmund"
  - "Eduardo"
  - "Edward"
  - "Edwin"
  - "Ei"
  - "Ekaterina"
  - "Elaine"
  - "Eleanor"
  - "Elena"
  - "Elias"
  - "Elisabeth"
  - "Elizabeth"
  - "Ellen"
  - "Ellyn"
  - "Elsa"
  - "Elspeth"
  - "Elvira"
  - "Eman"
  - "Emeline"
  - "Emily"
  - "Emine"
  - "Emma"
  - "Emmanuel"
  - "Enndolynn"
  - "Enrique"
  - "Eric"
  - "Erika"
  - "Ernest"
  - "Ernesto"
  - "Ester"
  - "Esther"
  - "Eunice"
  - "Eva"
  - "Evelyn"
  - "Evgeniy"
  - "Fabio"
  - "Faisal"
  - "Faith"
  - "Farfelee"
  - "Farida"
  - "Farzana"
  - "Fatemeh"
  - "Fatima"
  - "Fatma"
  - "Fatoumata"
  - "Favian"
  - "Felipe"
  - "Felix"
  - "Fendrel"
  - "Fernando"
  - "Florence"
  - "Forthwind"
  - "Francesco"
  - "Francis"
  - "Francisca"
  - "Francisco"
  - "Francois"
  - "Frank"
  - "Fred"
  - "Frederick"
  - "Gabriel"
  - "Gabriela"
  - "Galina"
  - "Ganesh"
  - "Gang"
  - "Ganga"
  - "Gary"
  - "Gavin"
  - "Geoffrey"
  - "George"
  - "Gerald"
  - "Gerardo"
  - "Gerhard"
  - "Ghulam"
  - "Gilbert"
  - "Gilberto"
  - "Giovanni"
  - "Gita"
  - "Giuseppe"
  - "Gladys"
  - "Gloria"
  - "Gloriana"
  - "Godiva"
  - "Good"
  - "Gopal"
  - "Gorvenal"
  - "Grace"
  - "Gregory"
  - "Guadalupe"
  - "Guillermo"
  - "Guinevere"
  - "Gul"
  - "Guohua"
  - "Guoliang"
  - "Guoqiang"
  - "Gussalen"
  - "Gustavo"
  - "Guy"
  - "Gwendolynn"
  - "Ha"
  - "Habib"
  - "Habiba"
  - "Hadrian"
  - "Hai"
  - "Haibo"
  - "Haitao"
  - "Haiyan"
  - "Haiying"
  - "Haji"
  - "Halima"
  - "Halyna"
  - "Hamid"
  - "Hamza"
  - "Han"
  - "Hana"
  - "Hanan"
  - "Hang"
  - "Hans"
  - "Hari"
  - "Hasan"
  - "Hassan"
  - "Hatice"
  - "Hawa"
  - "Heather"
  - "Heba"
  - "Hector"
  - "Heinz"
  - "Helen"
  - "Helena"
  - "Helewys"
  - "Helga"
  - "Henry"
  - "Herbert"
  - "Hieu"
  - "Hilda"
  - "Hildegard"
  - "Hiroshi"
  - "Hoa"
  - "Hoang"
  - "Hong"
  - "Hongmei"
  - "Hongwei"
  - "Hongyan"
  - "Hossein"
  - "Huan"
  - "Hugo"
  - "Hui"
  - "Huimin"
  - "Hung"
  - "Huong"
  - "Hussein"
  - "Huy"
  - "Ian"
  - "Ibrahim"
  - "Ida"
  - "Igor"
  - "Ilya"
  - "Iman"
  - "Imran"
  - "Ingrid"
  - "Irene"
  - "Irina"
  - "Irma"
  - "Isa"
  - "Isaac"
  - "Isabel"
  - "Isabelle"
  - "Iseult"
  - "Ismail"
  - "Isolde"
  - "Issa"
  - "Ivan"
  - "Jack"
  - "Jacob"
  - "Jacqueline"
  - "Jacquelyn"
  - "Jacques"
  - "Jaime"
  - "Jamal"
  - "Jamila"
  - "Jan"
  - "Jane"
  - "Janet"
  - "Janshai"
  - "Jarin"
  - "Jasmine"
  - "Jason"
  - "Javier"
  - "Jay"
  - "Jean"
  - "Jeanne"
  - "Jeff"
  - "Jeffrey"
  - "Jennifer"
  - "Jenny"
  - "Jerry"
  - "Jessica"
  - "Jesus"
  - "Jianfeng"
  - "Jianguo"
  - "Jianhua"
  - "Jianhui"
  - "Jianjun"
  - "Jianmin"
  - "Jianming"
  - "Jianping"
  - "Jianwei"
  - "Jianxin"
  - "Jianzhong"
  - "Jim"
  - "Jimmy"
  - "Jin"
  - "Jingjing"
  - "Jinhua"
  - "Jitendra"
  - "Joan"
  - "Joanna"
  - "Joao"
  - "Joaquim"
  - "Joe"
  - "Joel"
  - "John"
  - "Jonathan"
  - "Jorge"
  - "Jose"
  - "Josef"
  - "Josefa"
  - "Josefina"
  - "Joseph"
  - "Josephine"
  - "Joshua"
  - "Josselyn"
  - "José"
  - "Joy"
  - "Joyce"
  - "Juan"
  - "Juana"
  - "Judith"
  - "Judy"
  - "Julia"
  - "Juliana"
  - "Julie"
  - "Julio"
  - "Julius"
  - "Junjie"
  - "Justice"
  - "Justin"
  - "Jyoti"
  - "Ka"
  - "Kai"
  - "Kailash"
  - "Kalpana"
  - "Kamal"
  - "Kamala"
  - "Kamla"
  - "Karen"
  - "Karim"
  - "Karin"
  - "Karina"
  - "Karl"
  - "Kassa"
  - "Katarzyna"
  - "Katelyn"
  - "Kathleen"
  - "Kathy"
  - "Katrina"
  - "Katsumi"
  - "Kavita"
  - "Kaylein"
  - "Keith"
  - "Kelly"
  - "Ken"
  - "Kenji"
  - "Kenneth"
  - "Kevin"
  - "Khadija"
  - "Khaled"
  - "Khalid"
  - "Kim"
  - "Kimberly"
  - "Kiran"
  - "Kirill"
  - "Klaus"
  - "Konstantin"
  - "Krea"
  - "Krishna"
  - "Kristina"
  - "Krzysztof"
  - "Kseniya"
  - "Kun"
  - "Kyaw"
  - "Laila"
  - "Lakshmi"
  - "Laksmi"
  - "Lal"
  - "Lalita"
  - "Lan"
  - "Laoshi"
  - "Larry"
  - "Laura"
  - "Lawrence"
  - "Laxmi"
  - "Le"
  - "Lee"
  - "Lei"
  - "Leila"
  - "Leo"
  - "Leofrick"
  - "Leonard"
  - "Leonardo"
  - "Letholdus"
  - "Leticia"
  - "Li"
  - "Lidia"
  - "Lief"
  - "Lihong"
  - "Lihua"
  - "Lijuan"
  - "Lijun"
  - "Lila"
  - "Lilian"
  - "Liliana"
  - "Liming"
  - "Lin"
  - "Lina"
  - "Linda"
  - "Ling"
  - "Lingling"
  - "Linh"
  - "Liping"
  - "Lisa"
  - "Lixin"
  - "Liying"
  - "Long"
  - "Lord"
  - "Loreena"
  - "Lorena"
  - "Louis"
  - "Louise"
  - "Luanda"
  - "Lucas"
  - "Lucia"
  - "Luciano"
  - "Lucy"
  - "Luis"
  - "Luisa"
  - "Luiz"
  - "Luz"
  - "Lwin"
  - "Lydia"
  - "Lyubov"
  - "Lyudmila"
  - "Lyudmyla"
  - "Ma"
  - "Madina"
  - "Maerwynn"
  - "Magdalena"
  - "Maha"
  - "Mahdi"
  - "Mahendra"
  - "Mahesh"
  - "Mahmoud"
  - "Mai"
  - "Maksim"
  - "Malkyn"
  - "Mamadou"
  - "Mamta"
  - "Man"
  - "Manfred"
  - "Manju"
  - "Manoel"
  - "Manoj"
  - "Manuel"
  - "Manuela"
  - "Marc"
  - "Marcel"
  - "Marcelo"
  - "Marcia"
  - "Marcin"
  - "Marco"
  - "Marcos"
  - "Margaret"
  - "Margarita"
  - "Maria"
  - "Mariam"
  - "Mariama"
  - "Mariana"
  - "Marianne"
  - "Marie"
  - "Marilyn"
  - "Marina"
  - "Mario"
  - "Mariya"
  - "Mark"
  - "Marlene"
  - "Marta"
  - "Martha"
  - "Martin"
  - "Martina"
  - "Martine"
  - "Marwa"
  - "Mary"
  - "Maryam"
  - "Maryia"
  - "Masako"
  - "Masmaat"
  - "Masoumeh"
  - "Matilda"
  - "Matthew"
  - "Maurice"
  - "Maya"
  - "Mehmet"
  - "Mei"
  - "Melanie"
  - "Melissa"
  - "Meng"
  - "Mercedes"
  - "Mercy"
  - "Merek"
  - "Mi"
  - "Michael"
  - "Michel"
  - "Michele"
  - "Michelle"
  - "Miguel"
  - "Mike"
  - "Mikhail"
  - "Millicent"
  - "Min"
  - "Mina"
  - "Ming"
  - "Minh"
  - "Mira"
  - "Mirabelle"
  - "Miriam"
  - "Mo"
  - "Mohamad"
  - "Mohamed"
  - "Mohammad"
  - "Mohammed"
  - "Mohan"
  - "Mohsen"
  - "Mona"
  - "Monica"
  - "Monika"
  - "Monique"
  - "Moses"
  - "Mostafa"
  - "Moussa"
  - "Muhamad"
  - "Muhammad"
  - "Muhammed"
  - "Mukesh"
  - "Munni"
  - "Muriel"
  - "Musa"
  - "Mustafa"
  - "Mustapha"
  - "Myat"
  - "Mária"
  - "Na"
  - "Nabil"
  - "Nada"
  - "Nadezhda"
  - "Nadia"
  - "Nam"
  - "Nan"
  - "Nana"
  - "Nancy"
  - "Narayan"
  - "Naresh"
  - "Naseem"
  - "Nasir"
  - "Nasreen"
  - "Nasrin"
  - "Natalia"
  - "Natalya"
  - "Nathalie"
  - "Nelson"
  - "Nestor"
  - "Nga"
  - "Ngoc"
  - "Nguyen"
  - "Ni"
  - "Nicholas"
  - "Nicolas"
  - "Nicole"
  - "Nikita"
  - "Nikolay"
  - "Nina"
  - "Ning"
  - "Nirmala"
  - "Noel"
  - "Noor"
  - "Nora"
  - "Norma"
  - "Nour"
  - "Nur"
  - "Nurul"
  - "Nushi"
  - "Nusrat"
  - "Nykolai"
  - "O"
  - "Oksana"
  - "Oleg"
  - "Olga"
  - "Olha"
  - "Oliver"
  - "Olivier"
  - "Om"
  - "Omar"
  - "Orlando"
  - "Oscar"
  - "Osman"
  - "Pa"
  - "Pablo"
  - "Pamela"
  - "Pankaj"
  - "Paola"
  - "Parvati"
  - "Pascal"
  - "Patricia"
  - "Patrick"
  - "Paul"
  - "Paula"
  - "Paulina"
  - "Pauline"
  - "Paulo"
  - "Pavel"
  - "Pedro"
  - "Pei"
  - "Peng"
  - "Peronell"
  - "Peter"
  - "Petr"
  - "Petra"
  - "Peyton"
  - "Philip"
  - "Philippe"
  - "Phrowenia"
  - "Phuong"
  - "Phyo"
  - "Pierre"
  - "Ping"
  - "Piotr"
  - "Pradip"
  - "Prakash"
  - "Pramila"
  - "Pramod"
  - "Prem"
  - "Priyanka"
  - "Punam"
  - "Pushpa"
  - "Qiang"
  - "Qing"
  - "Qinghua"
  - "Qiong"
  - "Quan"
  - "Quinn"
  - "Qun"
  - "Rabia"
  - "Rachel"
  - "Radha"
  - "Rafael"
  - "Rahul"
  - "Raimundo"
  - "Rainydayas"
  - "Raj"
  - "Raja"
  - "Rajendra"
  - "Rajesh"
  - "Raju"
  - "Rakesh"
  - "Ram"
  - "Rama"
  - "Ramesh"
  - "Ramon"
  - "Ran"
  - "Rana"
  - "Rani"
  - "Ranjit"
  - "Raquel"
  - "Rashid"
  - "Raul"
  - "Ravi"
  - "Ravindra"
  - "Raymond"
  - "Rebecca"
  - "Regina"
  - "Rekha"
  - "Rene"
  - "Renu"
  - "Reza"
  - "Ricardo"
  - "Richard"
  - "Rina"
  - "Rita"
  - "Robert"
  - "Roberto"
  - "Robin"
  - "Rodolfo"
  - "Rodrigo"
  - "Roger"
  - "Roland"
  - "Roman"
  - "Ronald"
  - "Rong"
  - "Rosa"
  - "Rosario"
  - "Rose"
  - "Rosemary"
  - "Rowan"
  - "Roy"
  - "Ruben"
  - "Rulf"
  - "Ruslan"
  - "Rustam"
  - "Ruth"
  - "Ryan"
  - "Ryia"
  - "Sabina"
  - "Sabine"
  - "Sabrina"
  - "Sachiko"
  - "Sadia"
  - "Sadon"
  - "Saeed"
  - "Sai"
  - "Said"
  - "Sakina"
  - "Salah"
  - "Saleh"
  - "Salim"
  - "Salma"
  - "Salvador"
  - "Sam"
  - "Samia"
  - "Samina"
  - "Samir"
  - "Samira"
  - "Samuel"
  - "Sandeep"
  - "Sandra"
  - "Sangeeta"
  - "Sangita"
  - "Sani"
  - "Sanjay"
  - "Santos"
  - "Santosh"
  - "Sara"
  - "Sarah"
  - "Saraswati"
  - "Sarita"
  - "Saroj"
  - "Satish"
  - "Savita"
  - "Savitri"
  - "Sayed"
  - "Scott"
  - "Sebastian"
  - "Seraphina"
  - "Sergey"
  - "Sergio"
  - "Serhei"
  - "Seyyed"
  - "Shah"
  - "Shahid"
  - "Shakuntala"
  - "Shan"
  - "Shankar"
  - "Shanshan"
  - "Shanti"
  - "Sharmin"
  - "Sharon"
  - "Sheikh"
  - "Sheila"
  - "Shigeru"
  - "Shila"
  - "Shirley"
  - "Shiv"
  - "Shobha"
  - "Shu"
  - "Shuang"
  - "Shyam"
  - "Silvia"
  - "Sima"
  - "Simon"
  - "Simone"
  - "Sir"
  - "Sita"
  - "Siti"
  - "Smt"
  - "Sofia"
  - "Solomon"
  - "Son"
  - "Song"
  - "Sonia"
  - "Sophie"
  - "Sri"
  - "Stefan"
  - "Stella"
  - "Stephanie"
  - "Stephen"
  - "Steven"
  - "Subhash"
  - "Sultan"
  - "Suman"
  - "Sumitra"
  - "Sunday"
  - "Sunil"
  - "Sunita"
  - "Surendra"
  - "Suresh"
  - "Susan"
  - "Susana"
  - "Sushila"
  - "Svetlana"
  - "Sybbyl"
  - "Syed"
  - "Sylvia"
  - "Sylvie"
  - "Ta"
  - "Tadesse"
  - "Tamara"
  - "Tania"
  - "Tara"
  - "Tatiana"
  - "Tatyana"
  - "Teresa"
  - "Terrowin"
  - "Terry"
  - "Terryn"
  - "Than"
  - "Thanh"
  - "Thao"
  - "Thea"
  - "Theresa"
  - "Therese"
  - "Thierry"
  - "Thomas"
  - "Thu"
  - "Thuy"
  - "Tian"
  - "Tien"
  - "Tim"
  - "Timothy"
  - "Tina"
  - "Tingting"
  - "Tomas"
  - "Tomasz"
  - "Tong"
  - "Tony"
  - "Trang"
  - "Tristan"
  - "Tu"
  - "Tuan"
  - "Tun"
  - "Tybalt"
  - "Ulric"
  - "Uma"
  - "Umar"
  - "Umesh"
  - "Urmila"
  - "Ursula"
  - "Usha"
  - "Usman"
  - "Valentina"
  - "Valentyna"
  - "Valerie"
  - "Van"
  - "Vanessa"
  - "Vasylyi"
  - "Vera"
  - "Veronica"
  - "Vicente"
  - "Victor"
  - "Victoria"
  - "Vijay"
  - "Viktor"
  - "Viktoriya"
  - "Vincent"
  - "Vinod"
  - "Virginia"
  - "Vladimir"
  - "Vladymyr"
  - "Wai"
  - "Walter"
  - "Wei"
  - "Weidong"
  - "Weihua"
  - "Weimin"
  - "Weiming"
  - "Weiping"
  - "Weiwei"
  - "Wendy"
  - "Wenjie"
  - "Wenjing"
  - "Wenjun"
  - "Werner"
  - "William"
  - "Wilson"
  - "Winifred"
  - "Wolfgang"
  - "Xalvador"
  - "Xian"
  - "Xiang"
  - "Xiaodong"
  - "Xiaofeng"
  - "Xiaohong"
  - "Xiaohua"
  - "Xiaohui"
  - "Xiaojun"
  - "Xiaoli"
  - "Xiaolin"
  - "Xiaoling"
  - "Xiaomei"
  - "Xiaomin"
  - "Xiaoming"
  - "Xiaoping"
  - "Xiaoqing"
  - "Xiaowei"
  - "Xiaoxia"
  - "Xiaoyan"
  - "Xiaoying"
  - "Xiaoyu"
  - "Xin"
  - "Xing"
  - "Xuan"
  - "Xuemei"
  - "Yan"
  - "Yanhong"
  - "Yanhua"
  - "Yanling"
  - "Yanping"
  - "Yanyan"
  - "Yasmin"
  - "Yen"
  - "Yin"
  - "Ying"
  - "Yingying"
  - "Yoko"
  - "Yolanda"
  - "Yong"
  - "Yousef"
  - "Ysmay"
  - "Yu"
  - "Yuanyuan"
  - "Yue"
  - "Yuhua"
  - "Yuliya"
  - "Yumei"
  - "Yun"
  - "Yuping"
  - "Yuriy"
  - "Yusuf"
  - "Yvan"
  - "Yvonne"
  - "Zahra"
  - "Zainab"
  - "Zane"
  - "Zaw"
  - "Zhen"
  - "Zhenhua"
  - "Zhi"
  - "Zhigang"
  - "Zhihong"
  - "Zhihua"
  - "Zhihui"
  - "Zhijian"
  - "Zhijun"
  - "Zhiming"
  - "Zhiping"
  - "Zhiqiang"
  - "Zhiwei"
  - "Zhiyong"
  - "Zin"
villager_names:

#
# Keep disabled if you are not sure what this is?
debug: false
